spring.datasource.url=jdbc:postgresql://db.wdjztnkjswxsjzynkifq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ronizera12230

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=5b8e3f2a1d4c7e9b0f6a2d5c8e1b4f7a9d2c5e8b1f4a7d0c3e6b9f2a5d8c1e4
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
