spring.application.name=estoque
server.port=8081

#h2
spring.datasource.url=jdbc:h2:mem:estoque
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#console visual h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JWT
jwt.secret=5b8e3f2a1d4c7e9b0f6a2d5c8e1b4f7a9d2c5e8b1f4a7d0c3e6b9f2a5d8c1e4
jwt.expiration=86400000
